/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthRefreshTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'replacedBy', 'revokedAt', 'sessionId', 'tokenHash', 'userId'] as const
  $columns = AuthRefreshTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare replacedBy: string | null
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare sessionId: string
  @column()
  declare tokenHash: string
  @column()
  declare userId: string
}

export class AuthSessionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'lastActivityAt', 'revokedAt', 'userId'] as const
  $columns = AuthSessionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastActivityAt: DateTime
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare userId: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'name', 'passwordHash', 'role', 'slug', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare passwordHash: string
  @column()
  declare role: any
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
