/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AgendamentoCancelamentoSchema extends BaseModel {
  static $columns = ['agendamentoId', 'createdAt', 'id', 'motivo'] as const
  $columns = AgendamentoCancelamentoSchema.$columns
  @column()
  declare agendamentoId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare motivo: string | null
}

export class AgendamentoSchema extends BaseModel {
  static $columns = ['clienteEmail', 'clienteNome', 'clienteWhatsapp', 'createdAt', 'dataHoraFim', 'dataHoraInicio', 'id', 'notasInternas', 'servicoId', 'status', 'statusConfirmacao', 'updatedAt', 'userId'] as const
  $columns = AgendamentoSchema.$columns
  @column()
  declare clienteEmail: string | null
  @column()
  declare clienteNome: string
  @column()
  declare clienteWhatsapp: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare dataHoraFim: DateTime
  @column.dateTime()
  declare dataHoraInicio: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare notasInternas: string | null
  @column()
  declare servicoId: string
  @column()
  declare status: any
  @column()
  declare statusConfirmacao: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class AuthRefreshTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'replacedBy', 'revokedAt', 'sessionId', 'tokenHash', 'userId'] as const
  $columns = AuthRefreshTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare replacedBy: string | null
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare sessionId: string
  @column()
  declare tokenHash: string
  @column()
  declare userId: string
}

export class AuthSessionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'lastActivityAt', 'revokedAt', 'userId'] as const
  $columns = AuthSessionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastActivityAt: DateTime
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare userId: string
}

export class BloqueiosAgendumSchema extends BaseModel {
  static $columns = ['createdAt', 'data', 'id', 'motivo', 'userId'] as const
  $columns = BloqueiosAgendumSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare data: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare motivo: string
  @column()
  declare userId: string
}

export class BookingAttemptSchema extends BaseModel {
  static $columns = ['createdAt', 'detalhes', 'id', 'resultado', 'servicoId', 'slotDatetime', 'userId'] as const
  $columns = BookingAttemptSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare detalhes: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare resultado: string
  @column()
  declare servicoId: string | null
  @column.dateTime()
  declare slotDatetime: DateTime
  @column()
  declare userId: string
}

export class ConfiguracoeSchema extends BaseModel {
  static $columns = ['bannerSubtitulo', 'bannerTitulo', 'corPrincipal', 'corSecundaria', 'createdAt', 'endereco', 'especialidade', 'heroSubtitulo', 'heroTitulo', 'heroTituloDestaque', 'id', 'instagram', 'logoUrl', 'nomeExibicao', 'nomeProfissional', 'primeiraVisita', 'tagline', 'updatedAt', 'userId', 'whatsapp'] as const
  $columns = ConfiguracoeSchema.$columns
  @column()
  declare bannerSubtitulo: string | null
  @column()
  declare bannerTitulo: string | null
  @column()
  declare corPrincipal: string
  @column()
  declare corSecundaria: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare endereco: string | null
  @column()
  declare especialidade: string | null
  @column()
  declare heroSubtitulo: string | null
  @column()
  declare heroTitulo: string | null
  @column()
  declare heroTituloDestaque: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare instagram: string | null
  @column()
  declare logoUrl: string | null
  @column()
  declare nomeExibicao: string | null
  @column()
  declare nomeProfissional: string | null
  @column()
  declare primeiraVisita: boolean
  @column()
  declare tagline: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
  @column()
  declare whatsapp: string | null
}

export class DisponibilidadeSchema extends BaseModel {
  static $columns = ['createdAt', 'dias', 'id', 'intervaloAtendimentoMinutos', 'updatedAt', 'userId'] as const
  $columns = DisponibilidadeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dias: any
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare intervaloAtendimentoMinutos: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class ServicoSchema extends BaseModel {
  static $columns = ['ativo', 'createdAt', 'descricao', 'duracaoMinutos', 'emoji', 'id', 'nome', 'preco', 'updatedAt', 'userId'] as const
  $columns = ServicoSchema.$columns
  @column()
  declare ativo: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare descricao: string | null
  @column()
  declare duracaoMinutos: number
  @column()
  declare emoji: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare nome: string
  @column()
  declare preco: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'name', 'passwordHash', 'role', 'slug', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare passwordHash: string
  @column()
  declare role: any
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
