/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Disponibilidade: () => import('#controllers/disponibilidade_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Servicos: () => import('#controllers/servicos_controller'),
  Users: () => import('#controllers/users_controller'),
}
